# TODO this should be automatically generated by running another setup.py command
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import imp, glob, os
    try:
        __file__ = glob.glob(f"{os.path.dirname(__file__)}/build/*.so")[0]
    except IndexError:
        raise Exception("Did not find native dynamic library for fgb, did you run setup.py to build it?")
    __loader__ = None; del __bootstrap__, __loader__
    imp.load_dynamic(__name__,__file__)
__bootstrap__()
